appId: com.fertilityfocus.ovusense3
name: "Settings - Password Empty Fields, Personal Details & Notifications (test@)"
---
# Clean login
- runFlow:
    file: helpers/login_clean.yaml
    env:
      EMAIL: "test@ovusense.com"
      PASSWORD: "ovutest?0"
# Test body
- runFlow: bodies/39_settings_password_personal_body.yaml
# Cleanup
- clearState
